### PR TITLE
Update submodules for g2tmpl _d removal and cmake find_package updates

### PR DESCRIPTION
**Pull request by kgerheiser**

### CODE REVIEW

**Comment by kgerheiser** [comment]
I should probably update the other cmake submodules first before I do this

**Comment by climbfuji** [comment]
You can also leave this to me and my superb copy & paste template. I'll do that at the end of the day, who knows how many more cmake changes will be coming.

**Comment by kgerheiser** [comment]
That would be great, I'll close this then

**Comment by climbfuji** [comment]
Thanks. Enjoy skiing.

**Pull request closed without merging**
