### PR TITLE
Deploy modulefiles for NCEPLIBS

### PR DESCRIPTION
**Pull request by aerorahul**
This PR:
- **is an extension of #76**
- adds templated Lua modulefiles for each of the individual NCEPLIBS libraries and
- creates a cmake target `deploy` that will create a script to deploy the modulefiles replacing the installation path and the version number in the final modulefile for the library.

This will make it easy to clone, build, test and deploy these libraries (and associated modules) on machines where these libraries are typically maintained as modules.

The tree structure of the module files is:
```
<modules-prefix>
├── bacio
│   └── bacio-x.y.z.lua
├── nceppost
│   └── nceppost-feature-tryme.lua
└── w3nco
    └── w3nco-develop.lua
```

This module structure is reflective of the install tree structure as seen in #76.

**The modules on these machines need to be slightly updated to address the updated tree structure**
E.g. on Orion, HERA and WCOSS-Dell, the modulefiles are located under:

Orion:
```
module use -a /work/noaa/da/rmahajan/opt/modulefiles/mpi/intel/2018/impi/2018/nceplibs
```

Hera:
```
module use -a /scratch1/NCEPDEV/stmp2/Rahul.Mahajan/opt/modulefiles/mpi/intel/2018.0.5.274/impi/2018.0.4/nceplibs
```

WCOSS Dell 3:
```
module use -a /gpfs/dell2/emc/modeling/save/Rahul.Mahajan/opt/modulefiles/mpi/ips/18.0.1.163/impi/18.0.1/nceplibs
```

Since there are no automated regression tests, I would appreciate if someone from the application groups of  UFS_UTILS, EMC_post, and UFS could test these libraries with their respective applications on the above platforms. 

Here is an example of my installation workflow:
```
module load intel
module load impi
module load netcdf

export CC=mpiicc
export FC=mpiifort
export CXX=mpiicpc

prefix=/path/to/install/nceplibs

git clone -b feature/umbrella-modules https://github.com/noaa-emc/nceplibs
cd nceplibs
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$prefix -DDEPLOY=ON ..
make -j 6
make deploy
```

An example script on `Hera` is here:
```
/scratch1/NCEPDEV/stmp2/Rahul.Mahajan/test/UFS/src/build_nceplibs.sh
```

### CODE REVIEW

**Review by kgerheiser — APPROVED** [review]

**Comment by kgerheiser** [comment]
It all looks good to me

**Comment by climbfuji** [comment]
For my understanding, the version of the different libraries is part of the directory tree, not the names of the libraries anymore, right?

**Comment by aerorahul** [comment]
> For my understanding, the version of the different libraries is part of the directory tree, not the names of the libraries anymore, right?

I don't understand the question.
NCEPLIBS-* have a VERSION associated with them.  The name of the modulefile is that VERSION number.
Does that answer your question, that I don't understand?

**Comment by climbfuji** [comment]
> > For my understanding, the version of the different libraries is part of the directory tree, not the names of the libraries anymore, right?
> 
> I don't understand the question.
> NCEPLIBS-* have a VERSION associated with them. The name of the modulefile is that VERSION number.
> Does that answer your question, that I don't understand?

Sorry, my question wasn't clear. How does the umbrella build install the different libraries, i.e. what's the directory structure, and where in that structure is the library version encoded?

**Comment by aerorahul** [comment]
> > > For my understanding, the version of the different libraries is part of the directory tree, not the names of the libraries anymore, right?
> > 
> > 
> > I don't understand the question.
> > NCEPLIBS-* have a VERSION associated with them. The name of the modulefile is that VERSION number.
> > Does that answer your question, that I don't understand?
> 
> Sorry, my question wasn't clear. How does the umbrella build install the different libraries, i.e. what's the directory structure, and where in that structure is the library version encoded?

Aah, thats better.
Here is a snapshot of the installation directory structure:
```
$> tree -L 2 <CMAKE_INSTALL_PREFIX>
<CMAKE_INSTALL_PREFIX>/
├── bacio
│   ├── include_4
│   ├── include_8
│   └── lib
├── crtm
│   ├── include
│   └── lib
├── g2
│   ├── include_4
│   ├── include_d
│   └── lib
├── g2tmpl
│   ├── include
│   ├── lib
│   └── share
├── gfsio
│   ├── include
│   └── lib
├── ip
│   ├── include_4
│   ├── include_8
│   ├── include_d
│   └── lib
├── landsfcutil
│   ├── include_4
│   ├── include_d
│   └── lib
├── nceppost
│   ├── include
│   ├── lib
│   └── share
├── nemsio
│   ├── bin
│   ├── include
│   └── lib
├── nemsiogfs
│   ├── include
│   └── lib
├── sfcio
│   ├── include
│   └── lib
├── sigio
│   ├── include
│   └── lib
├── sp
│   ├── include_4
│   ├── include_8
│   ├── include_d
│   └── lib
├── w3emc
│   ├── include_4
│   ├── include_8
│   ├── include_d
│   └── lib
└── w3nco
    ├── include_4
    ├── include_8
    ├── include_d
    └── lib
```

**Comment by climbfuji** [comment]
Thanks. So, for the example of g2tmpl, the directory structure would be
```
$> tree -L 2 <CMAKE_INSTALL_PREFIX>
<CMAKE_INSTALL_PREFIX>/
...
├── g2tmpl
│   ├── include
│   ├── lib
│   ├── lib/libg2tmpl.a
│   └── share
...
```
So the information on which versions of the individual libraries you are using is the modulefile. Previously, the version of g2tmpl was also included in the name of the library (but this was not done consistently for all libraries, I guess, and it doesn't make sense to me).

I am wondering whether it would be better for the umbrella build to have
```
$> tree -L 2 <CMAKE_INSTALL_PREFIX>
<CMAKE_INSTALL_PREFIX>/
...
├── g2tmpl-x.y.z
│   ├── include
│   ├── lib
│   ├── lib/libg2tmpl.a
│   └── share
...
```
so that the different versions for the NCEPLIBS-* are also visible from the directory structure. Otherwise, how do I know when I browse
`<CMAKE_INSTALL_PREFIX> = NCEPLIBS-1.1.0`, for example. what the versions underneath the umbrella build are?

**Comment by aerorahul** [comment]
> Thanks. So, for the example of g2tmpl, the directory structure would be
> 
> ```
> $> tree -L 2 <CMAKE_INSTALL_PREFIX>
> <CMAKE_INSTALL_PREFIX>/
> ...
> ├── g2tmpl
> │   ├── include
> │   ├── lib
> │   ├── lib/libg2tmpl.a
> │   └── share
> ...
> ```
> 
> So the information on which versions of the individual libraries you are using is the modulefile. Previously, the version of g2tmpl was also included in the name of the library (but this was not done consistently for all libraries, I guess, and it doesn't make sense to me).
> 
> I am wondering whether it would be better for the umbrella build to have
> 
> ```
> $> tree -L 2 <CMAKE_INSTALL_PREFIX>
> <CMAKE_INSTALL_PREFIX>/
> ...
> ├── g2tmpl-x.y.z
> │   ├── include
> │   ├── lib
> │   ├── lib/libg2tmpl.a
> │   └── share
> ...
> ```
> 
> so that the different versions for the NCEPLIBS-* are also visible from the directory structure. Otherwise, how do I know when I browse
> `<CMAKE_INSTALL_PREFIX> = NCEPLIBS-1.1.0`, for example. what the versions underneath the umbrella build are?

I definitely want to have the directory structure contain the version number such as:
```
g2tmpl
└── x.y.z
    ├── include
    └── lib
```
This will allow one to install multiple versions of the libraries in the same tree.
Besides, if you look at the modulefiles, there is no explicit reference to the VERSION number.
Lua takes care of that.

I suppose this can be next PR?

**Comment by climbfuji** [comment]
> > Thanks. So, for the example of g2tmpl, the directory structure would be
> > ```
> > $> tree -L 2 <CMAKE_INSTALL_PREFIX>
> > <CMAKE_INSTALL_PREFIX>/
> > ...
> > ├── g2tmpl
> > │   ├── include
> > │   ├── lib
> > │   ├── lib/libg2tmpl.a
> > │   └── share
> > ...
> > ```
> > 
> > 
> > So the information on which versions of the individual libraries you are using is the modulefile. Previously, the version of g2tmpl was also included in the name of the library (but this was not done consistently for all libraries, I guess, and it doesn't make sense to me).
> > I am wondering whether it would be better for the umbrella build to have
> > ```
> > $> tree -L 2 <CMAKE_INSTALL_PREFIX>
> > <CMAKE_INSTALL_PREFIX>/
> > ...
> > ├── g2tmpl-x.y.z
> > │   ├── include
> > │   ├── lib
> > │   ├── lib/libg2tmpl.a
> > │   └── share
> > ...
> > ```
> > 
> > 
> > so that the different versions for the NCEPLIBS-* are also visible from the directory structure. Otherwise, how do I know when I browse
> > `<CMAKE_INSTALL_PREFIX> = NCEPLIBS-1.1.0`, for example. what the versions underneath the umbrella build are?
> 
> I definitely want to have the directory structure contain the version number such as:
> 
> ```
> g2tmpl
> └── x.y.z
>     ├── include
>     └── lib
> ```
> 
> This will allow one to install multiple versions of the libraries in the same tree.
> Besides, if you look at the modulefiles, there is no explicit reference to the VERSION number.
> Lua takes care of that.
> 
> I suppose this can be next PR?

Ok, I wasn't aware that this was an incremental solution. Yes, your suggestion `g2tmpl/x.y.z/...` is better.

**Review by climbfuji — APPROVED** [review]

**Comment by kgerheiser** [comment]
You would need to get the version from the repo to add to `CMAKE_INSTALL_PREFIX`. Would you read the `VERSION` file from the `configure` command in `ExternalProject_Add`? Just trying to think how you would do that.

**Comment by aerorahul** [comment]
> You would need to get the version from the repo to add to `CMAKE_INSTALL_PREFIX`. Would you read the `VERSION` file from the `configure` command in `ExternalProject_Add`? Just trying to think how you would do that.

Not necessarily. In the current PR, we are building develop versions of all the libraries, as shown by:
```
GIT_TAG   "develop"
```
We could just as easily provide a specific version, and construct the `GIT_TAG` appropriately. This information can be used in the installation prefix too.

Any other clever solutions?

**Comment by aerorahul** [comment]
> You would need to get the version from the repo to add to `CMAKE_INSTALL_PREFIX`. Would you read the `VERSION` file from the `configure` command in `ExternalProject_Add`? Just trying to think how you would do that.

@kgerheiser How is [this](https://github.com/NOAA-EMC/NCEPLIBS/pull/76/commits/779486217d9d7734587d583750b0a61c7c18643d) for a solution?

**Comment by aerorahul** [comment]
closing until issues with #76 are resolved.

**Comment by aerorahul** [comment]
@kgerheiser @climbfuji I think both your comments have been addressed in this PR.
I would appreciate a quick re-review.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
