### PR TITLE
Add grib_util library

### PR DESCRIPTION
**Pull request by kgerheiser**
Missed this one

### CODE REVIEW

**Comment by aerorahul** [comment]
I forgot to ask when prod_util was added in the previous PR. Why are utils being added to NCEPlibs? 
Do we add ufs_utils next?

**Comment by kgerheiser** [comment]
I was going for consistency with hpc-stack.

This repository is used to install on Cray since we can't use hpc-stack there.

They have the NCEPLIBS prefix

**Comment by kgerheiser** [comment]
Thoughts on this @edwardhartnett?

I can remove the utilities and keep them separate if they're outside the scope of this repo. Or we add them and keep them here.

**Comment by edwardhartnett** [comment]
Are they needed for UFS? I believe yes, since they are used by UPP, and that's part of the UFS system.

If so, we should add them to NCEPLIBS so that users can get them and build them.

**Comment by aerorahul** [comment]
By that argument, everything is part of the ufs. Should bring ufs-utils too.

prod_util and grib util are used in the workflow. Not in the build of the UFS model.

**Comment by edwardhartnett** [comment]
UFS_UTILS should probably also be added but we will leave that to the next version. ;-)

What is the distinction between the workflow and the model? Will community users not want to run the workflow?

**Comment by aerorahul** [comment]
No. Please do not ever add ufs utils to NCEPlibs. 
That is a slippery slope to follow. 
There is a big big distinction.

**Comment by edwardhartnett** [comment]
@aerorahul you must explain, not merely assert...

**Review by edwardhartnett — APPROVED** [review]

**Comment by aerorahul** [comment]
I can't in more or less 3-5 lines. 
And I don't want to write a story here.

**Comment by climbfuji** [comment]
> I can't in more or less 3-5 lines.
> And I don't want to write a story here.

Agreed, we had a long, long discussion about that in the past. UFS_UTILS is not part of NCEPLIBS. EMC_post (aka nceppost, upp) were considered as being not part of NCEPLIBS either when they were standalone applications, but now that the post library is used in the ufs-weather-model, this probably has changed.

**Pull request closed without merging**
