### PR TITLE
Create shell scripts to source for using NCEPLIBS, bugfixes and improvements for CMakeLists.txt, update submodule pointers

### PR DESCRIPTION
**Pull request by climbfuji**
- CMakeLists.txt: create shell scripts for bash and tcsh that can be sourced to set all necessary environment variables for NCEPLIBS and its dependencies. This scripts are created in `CMAKE_INSTALL_PREFIX/bin` with names `setenv_nceplibs.sh` and `setenv_nceplibs.csh`
- improved log output from cmake command
- fix macosx rpath issue (thanks, @kgerheiser)
- workaround for cmake completely ignoring "find_package(NetCDF REQUIRED)" on certain machines
- update of submodule pointers for cmake and several other submodules

### CODE REVIEW

**Comment by climbfuji** [comment]
Do not merge yet. At this point, I would like to get feedback from folks whether this is a reasonable approach to connect the NCEPLIBS with CIME or build.sh.

@mark-a-potts @kgerheiser @DusanJovic-NOAA @jedwards4b @rsdunlapiv

**Comment by jedwards4b** [comment]
I feel like this is all too much hand holding, it means that users have to follow your instructions to the letter or nothing works.   That's just my opinion, I can work with it if that's what you want to do.

**Comment by climbfuji** [comment]
Fair enough! You don't have to use, though. Our instructions could say that
> in order to build the model after the NCEPLIBS have been built, the following environment variables must be set: VAR1, VAR2, ... 
> Alternatively, a script is created as part of the NCEPLIBS build process that can be sourced and that sets all these variables for the user

Of course, without typos and in proper English ...

?

**Comment by climbfuji** [comment]
Just to explain the background a little more. My idea is that I want to keep the build of the entire system user-friendly but also flexible. There are three build steps:

1. Build NCEPLIBS-external (optional). All this stuff ends up in one directory `A`. If the user doesn't use NCEPLIBS-external, or if the user encounters an issue as described in the updated [README.md](https://github.com/NOAA-EMC/NCEPLIBS-external/), he or she will have to set some or all of the variables manually in order for step 2 to work: `Jasper_ROOT`, `PNG_ROOT`, `ZLIB_ROOT`, `ESMFMKFILE`, `HDF5_ROOT`, `NETCDF`.
2. Build NCEPLIBS (highly recommended/supported). All this stuff ends up in one directory `B=NCEPLIBS_DIR` (which can be `A`). If the user doesn't use the NCEPLIBS umbrella build, then he/she will have them in whatever place and will have the environment variables for the individual libraries set up correctly (because this person is a geek and/or has been working with NCEPLIBS and models that depend on it before, and knows about differences in versions etc; otherwise there is no reason to have them installed). Users who use the umbrella build should be able to use the same set of environment variables for step 3 then users who don't use the umbrella build: `NEMSIO_INC`, ...
3. Build model. This can be via CIME (UFS release, ufs-mrweather-app) or `build.sh` (ufs-weather-model). Both methods should be as close as possible in terms of how to configure the build. In particular if your goal is that new users as well as seasoned fv3gfs developers want to use CIME in the future.

There is exactly one point where all the information for building the model is present at the same time: at the end of the cmake step in 2. It knows all the dependencies (otherwise the build will fail), it knows the compilers (this is not yet in the shell scripts, and maybe doesn't need to go there - although it wouldn't hurt), and it knows the location and name of each NCEPLIBS environment variable required to build the model. It does make sense to present this information to the user, whatever the format is: print to screen, create a shell script to source. Printing to screen means the users have to copy and paste or type, and there is more than enough room for errors. Having the script allows the user to source it with little chance to get it wrong. And all CIME needs to do is use the environment variables (which are the same as for the preconfigured platforms, by the way) in its machine configuration xml. To me, this seems to make the entire chain much easier and less error-prone.

Lastly, I also believe that for a public release to the community, there can never be enough handholding. I used to be optimistic in the past, but as my dad always says: "A pessimist is an optimist with experience of life."

**Pull request merged**
