### PR TITLE
enable a DOWNLOAD_ONLY option

### PR DESCRIPTION
**Pull request by aerorahul**
`cmake -DDOWNLOAD_ONLY=ON`
will download everything to `./download`

`make tarball` will tar and zip `./download` into `nceplibs.tgz`
Transfer `nceplibs.tgz` to the the machine and untar in the umbrella directory.

`cmake -DUSE_LOCAL=ON`
will use the packages from ./download`

Give this a try.

### CODE REVIEW

**Comment by climbfuji** [comment]
Now we have two "competing" solutions, https://github.com/NOAA-EMC/NCEPLIBS/pull/108 and https://github.com/NOAA-EMC/NCEPLIBS/pull/109 - can you decide which you want to use, please?

**Comment by aerorahul** [comment]
That is what happens when you start a dumpster fire.

**Comment by climbfuji** [comment]
I believe @mark-a-potts said in the morning, right at the beginning of our email conversation, that he'd be working on this.

**Comment by aerorahul** [comment]
It must have flown past my flurry of emails. I will retract.

**Comment by climbfuji** [comment]
tell me ... I had 777 (yes, triple seven) emails when I came home from my vacation ...

**Comment by DusanJovic-NOAA** [comment]
Why is this PR closed?

**Comment by climbfuji** [comment]
> Why is this PR closed?

https://github.com/NOAA-EMC/NCEPLIBS/pull/109#issuecomment-679348482

**Comment by mark-a-potts** [comment]
I actually prefer @aerorahul's solution to mine.

**Comment by aerorahul** [comment]
@climbfuji 
I re-opened after discussing with @mark-a-potts 
Please try and let me know if this needs more work/improvements.

**Comment by climbfuji** [comment]
Thanks, Rahul I will try this on Endeavor right away.

**Review by mark-a-potts — COMMENTED** [review]
This works nicely for me. My only suggestion would be to change the option for USE_LOCAL to something like this--

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/download/nceplibs-bacio)
  option(USE_LOCAL     "Use locally downloaded components" ON)
else()
  option(USE_LOCAL     "Use locally downloaded components" OFF)
endif()

That will just automatically use the downloaded files if they are there, but can still be overridden, if desired.

**Comment by aerorahul** [comment]
> This works nicely for me. My only suggestion would be to change the option for USE_LOCAL to something like this--
> 
> if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/download/nceplibs-bacio)
> option(USE_LOCAL "Use locally downloaded components" ON)
> else()
> option(USE_LOCAL "Use locally downloaded components" OFF)
> endif()
> 
> That will just automatically use the downloaded files if they are there, but can still be overridden, if desired.

Doing that will imply an implicit choice on `bacio`.  So, if I only want to port  say crtm, that option won't work unless I check for crtm.  Same goes for say sigio, sfcio, wrf_io, bufr etc. (ones that don't depend on bacio)

I don't mind implementing the suggestion if it is generic, but I see a proliferation of if-else's trying to fit all combinations. 

But, I think we should implement an error check, where in, if `USE_LOCAL` is `ON`, the directory does exist.

**Comment by climbfuji** [comment]
This works just fine for me on Intel's Endeavor. I will add instructions on how to use this functionality in the usual place for the releases (NCEPLIBS-external -> develop -> doc/README_endeavor_intel.txt). I don't think we need to get more fancy than what we have right now. Thanks for implementing this so quickly.

**Review by mark-a-potts — APPROVED** [review]

**Review by kgerheiser — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]
> `cmake -DDOWNLOAD_ONLY=ON`
> will download everything to `./download`
> 
> `make tarball` will tar and zip `./download` into `nceplibs.tgz`
> Transfer `nceplibs.tgz` to the the machine and untar in the umbrella directory.
> 
> `cmake -DUSE_LOCAL=ON`
> will use the packages from ./download`
> 
> Give this a try.

I had to do
```
cmake -DDOWNLOAD_ONLY=ON ..
```
in a build directory followed by
```
make
```
in order to download it, but I haven't tried if
```
make tarball
```
triggers the download (i.e. the `make`) step automatically if not yet done. Either way, this works totally fine and serves our purposes well.

**Comment by aerorahul** [comment]
@climbfuji 
Thanks for testing.
I made two more pushes, 1 is a clean-up and other is a dependency for tarball.
You can now do `make tarball` and it will download the sources thus eliminating an intermediate `make`

Please test again.

**Comment by climbfuji** [comment]
For what it's worth, what I will end up doing is to simply download the data and then rsync the entire NCEPLIBS directory. I don't need the tarball, just the data downloaded to `./download`. A machine w/o internet access won't be able to download `NCEPLIBS` either, hence the need to rsync everything.

**Comment by aerorahul** [comment]
> For what it's worth, what I will end up doing is to simply download the data and then rsync the entire NCEPLIBS directory. I don't need the tarball, just the data downloaded to `./download`. A machine w/o internet access won't be able to download `NCEPLIBS` either, hence the need to rsync everything.

@climbfuji That's fine, but please test this option.  Regardless the option should work.

**Comment by climbfuji** [comment]
> > For what it's worth, what I will end up doing is to simply download the data and then rsync the entire NCEPLIBS directory. I don't need the tarball, just the data downloaded to `./download`. A machine w/o internet access won't be able to download `NCEPLIBS` either, hence the need to rsync everything.
> 
> @climbfuji That's fine, but please test this option. Regardless the option should work.

Yes, I can confirm that it works. I just thought that `make download` would be a more consistent way of downloading everything to `./download` without creating a tarball.

**Pull request merged**
