### PR TITLE
Feature/cleanup pr2

### PR DESCRIPTION
**Pull request by aerorahul**
This PR:
- adds a .gitignore file
- adds a README.md file
- adds a VERSION file that provides version number of the library
- cleans up CMakeLists.txt

The CMakeLists.txt clean-up includes:
- adds a version to the project, along with languages
- uses standard build types and checks for supported compilers.
- removal of globbing of source files
- using a CMake defined variables where appropriate
- splits compiler flags into common, debug, release
- uses `add_compile_definitions` where appropriate instead of `compile_flags`
- removes `POSITION_INDEPENDENT_CODE`.  Libraries are built as `STATIC`. If `SHARED` is desired, this feature is automatically added by cmake.
- formatting using `cmake-format`

### CODE REVIEW

**Comment by mark-a-potts** [comment]
I was able to successfully build your branch on Hera and run both the stand alone model and the CIME-based workflow with the SMS_Lh3_D.C192.GFSv15p2 case.

**Comment by aerorahul** [comment]
Thanks @mark-a-potts

**Comment by aerorahul** [comment]
All: I have managed to mess up after todays series of commits to the various submodules.
For one, I see code changes in UFS_UTILS that I know I did not make.

**Comment by climbfuji** [comment]
Note. This PR is still pointing to Rahul's forks of the individual NCEPLIBS repos. I am going to merge this now, then walk through the repos and create a follow-up PR for all the repos that I could merge.

**Pull request merged**
