### PR TITLE
Tagged versions of the updated CMake builds

### PR DESCRIPTION
**Pull request by kgerheiser**
Left Post as develop. Should that be changed?

### CODE REVIEW

**Comment by aerorahul** [comment]
can we provide a SHA instead of develop for nceppost? That will be fixed and atleast known to a few that it worked.

**Comment by kgerheiser** [comment]
I took the latest develop commit

**Review by aerorahul — APPROVED** [review]
Looks good.

**Comment by aerorahul** [comment]
Can these be installed in a central place with the modules on all 4 machines?   Hera, Orion, Dell and Cray?

**Comment by DusanJovic-NOAA** [comment]
I am trying to install NCEPLIBS on Orion. I run cmake like this:
```
$ cmake .. -DCMAKE_C_COMPILER=icc -DCMAKE_Fortran_COMPILER=ifort
-- The C compiler identification is Intel 19.1.0.20191121
-- The Fortran compiler identification is Intel 19.1.0.20191121
```
but later when I run make I see that crtm, for example, is building using GNU compiler:
```
[  3%] Performing update step for 'crtm'
[  4%] Performing configure step for 'crtm'
-- The Fortran compiler identification is GNU 4.8.5
-- Check for working Fortran compiler: /bin/f95
-- Check for working Fortran compiler: /bin/f95 - works
```

Can we pass `CMAKE_C_COMPILER` and `CMAKE_Fortran_COMPILER` to all external projects.

**Comment by aerorahul** [comment]
@DusanJovic-NOAA 
Interesting.
I don't see that.
But, I also don't pass `-DCMake_C_COMPILER=icc -DCMAKE_Fortran_COMPILER=ifort` as command line arguments.

I simply do `FC=ifort CC=icc cmake ..`

I see that they should be equivalent, but am not sure why you are seeing the difference.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA @aerorahul do you think these libraries are ready to try on Cheyenne? We still can't run the inline post code there, because we don't have the proper NCEP libraries set up. This may be a good test, Cheyenne is one of the level-1 platforms for both MRW App v1.1 and SRW App v1.0.

If yes, are there any instructions on how to install the libraries?

**Comment by DusanJovic-NOAA** [comment]
`FC=ifort CC=icc cmake ..` works, but then I need to run make like `FC=ifort CC=icc make`, I can not just run `make`. I think if we pass `CMAKE_C_COMPILER` and `CMAKE_Fortran_COMPILER` to all external projects, specifying compiler name only once will be enough.

**Comment by aerorahul** [comment]
> @DusanJovic-NOAA @aerorahul do you think these libraries are ready to try on Cheyenne? We still can't run the inline post code there, because we don't have the proper NCEP libraries set up. This may be a good test, Cheyenne is one of the level-1 platforms for both MRW App v1.1 and SRW App v1.0.
> 
> If yes, are there any instructions on how to install the libraries?

@climbfuji 
Example usage with intel, impi.  Please adapt per your compiler set and distro
```
module load intel impi netcdf ... the usual stuff
export CC=mpiicc
export FC=mpiifort

cmake -DCMAKE_INSTALL_PREFIX=/path/to/install/nceplibs -DFLAT=ON -DDEPLOY=ON /path/to/src/nceplibs
make -j8
make deploy
```
Libraries will be installed under `/path/to/install/nceplibs`
Modulefiles (if you want to use them) will be at `/path/to/src/nceplibs/modules`

To use them:
```
module use /path/to/install/nceplibs/modules
module avail
module load bacio ....

cmake ..
```
or, in your application

`cmake -DCMAKE_PREFIX_PATH=/path/to/install/nceplibs ...`

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA @aerorahul do you think these libraries are ready to try on Cheyenne? We still can't run the inline post code there, because we don't have the proper NCEP libraries set up. This may be a good test, Cheyenne is one of the level-1 platforms for both MRW App v1.1 and SRW App v1.0.
> 
> If yes, are there any instructions on how to install the libraries?

@climbfuji We also need this libraries installed on Hera using GNU compilers.

**Comment by aerorahul** [comment]
> `FC=ifort CC=icc cmake ..` works, but then I need to run make like `FC=ifort CC=icc make`, I can not just run `make`. I think if we pass `CMAKE_C_COMPILER` and `CMAKE_Fortran_COMPILER` to all external projects, specifying compiler name only once will be enough.

I don't think that `FC=ifort CC=icc make` should be necessary, because CMake generators fill in the full path of the compiler in `build.cmake`.
What is different in your build environment from mine on Orion?
I

**Comment by DusanJovic-NOAA** [comment]
```
$ CC=icc FC=ifort cmake ..
-- The C compiler identification is Intel 19.1.0.20191121
-- The Fortran compiler identification is Intel 19.1.0.20191121
```
then:
```
$ make
Scanning dependencies of target prep2deploy
[  0%] Built target prep2deploy
Scanning dependencies of target crtm
[  1%] Creating directories for 'crtm'

[  4%] Performing configure step for 'crtm'
-- The Fortran compiler identification is GNU 4.8.5
-- Check for working Fortran compiler: /bin/f95
-- Check for working Fortran compiler: /bin/f95 - works
```

Anyway, I still think that we should support `-DCMAKE_C_COMPILER` and `-DCMAKE_Fortran_COMPILER` as a way of specifying compilers, instead of just requiring people to use environment variables.

**Comment by climbfuji** [comment]
> > @DusanJovic-NOAA @aerorahul do you think these libraries are ready to try on Cheyenne? We still can't run the inline post code there, because we don't have the proper NCEP libraries set up. This may be a good test, Cheyenne is one of the level-1 platforms for both MRW App v1.1 and SRW App v1.0.
> > If yes, are there any instructions on how to install the libraries?
> 
> @climbfuji We also need this libraries installed on Hera using GNU compilers.

Ok, thanks! I will give this a try on Hera with GNU first, and then move on to Cheyenne.

**Comment by aerorahul** [comment]
> ```
> $ CC=icc FC=ifort cmake ..
> -- The C compiler identification is Intel 19.1.0.20191121
> -- The Fortran compiler identification is Intel 19.1.0.20191121
> ```
> 
> then:
> 
> ```
> $ make
> Scanning dependencies of target prep2deploy
> [  0%] Built target prep2deploy
> Scanning dependencies of target crtm
> [  1%] Creating directories for 'crtm'
> 
> [  4%] Performing configure step for 'crtm'
> -- The Fortran compiler identification is GNU 4.8.5
> -- Check for working Fortran compiler: /bin/f95
> -- Check for working Fortran compiler: /bin/f95 - works
> ```
> 
> Anyway, I still think that we should support `-DCMAKE_C_COMPILER` and `-DCMAKE_Fortran_COMPILER` as a way of specifying compilers, instead of just requiring people to use environment variables.

I am fine with that, just trying to understand why the behavior is different between us on the same machine.

**Comment by kgerheiser** [comment]
Ok, I'll pass `CMAKE_Fortran_COMPILER`, etc to each project

**Comment by climbfuji** [comment]
> > > @DusanJovic-NOAA @aerorahul do you think these libraries are ready to try on Cheyenne? We still can't run the inline post code there, because we don't have the proper NCEP libraries set up. This may be a good test, Cheyenne is one of the level-1 platforms for both MRW App v1.1 and SRW App v1.0.
> > > If yes, are there any instructions on how to install the libraries?
> > 
> > 
> > @climbfuji We also need this libraries installed on Hera using GNU compilers.
> 
> Ok, thanks! I will give this a try on Hera with GNU first, and then move on to Cheyenne.

Hmm well this is a little annoying because I will need to build netcdf, ESMF etc. manually on hera.gnu. I have previously used nceplibs-external to do this, but this repository hasn't been updated since the update of the find-netcdf package.

**Comment by climbfuji** [comment]
> make deploy



> > @DusanJovic-NOAA @aerorahul do you think these libraries are ready to try on Cheyenne? We still can't run the inline post code there, because we don't have the proper NCEP libraries set up. This may be a good test, Cheyenne is one of the level-1 platforms for both MRW App v1.1 and SRW App v1.0.
> > If yes, are there any instructions on how to install the libraries?
> 
> @climbfuji
> Example usage with intel, impi. Please adapt per your compiler set and distro
> 
> ```
> module load intel impi netcdf ... the usual stuff
> export CC=mpiicc
> export FC=mpiifort
> 
> cmake -DCMAKE_INSTALL_PREFIX=/path/to/install/nceplibs -DFLAT=ON -DDEPLOY=ON /path/to/src/nceplibs
> make -j8
> make deploy
> ```
> 
> Libraries will be installed under `/path/to/install/nceplibs`
> Modulefiles (if you want to use them) will be at `/path/to/src/nceplibs/modules`
> 
> To use them:
> 
> ```
> module use /path/to/install/nceplibs/modules
> module avail
> module load bacio ....
> 
> cmake ..
> ```
> 
> or, in your application
> 
> `cmake -DCMAKE_PREFIX_PATH=/path/to/install/nceplibs ...`

All, let me just say that this is great - awesome job. It built and installed out of the box, and the modules loaded out of the box as well on Cheyenne using GNU 9.1.0. I'll still have to build the model and run it using those libraries. This will hopefully allow us to turn on the inline post capabilities on Cheyenne with both compilers (and later on hera when I have the underlying software stack built using NCEPLIBS-external).

**Comment by kgerheiser** [comment]
I pass CMAKE_C_COMPILER and CMAKE_Fortran_COMPILER to each library

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
