### PR TITLE
Use CMake's configure_file to create environment shell scripts

### PR DESCRIPTION
**Pull request by kgerheiser**
This is a lot more readable than appending line by line in the main CMakeLists

### CODE REVIEW

**Comment by climbfuji** [comment]
I like this! Let me pull it into my current development branch for the submodule pointer updates etc, and if all the tests work it will get merged automatically when my changes are merged. Ok?

**Comment by kgerheiser** [comment]
Roger

**Comment by climbfuji** [comment]
Is it possible - in the future, not for this PR - to push your branches to your fork and create the PR from there, please? We should try to keep this repository clean (and enable branch protection for the important branches).

**Comment by climbfuji** [comment]
This works fine on my Mac. Will run one more test on gaea.

**Comment by climbfuji** [comment]
This works on gaea as well. See PR https://github.com/NOAA-EMC/NCEPLIBS/pull/47, yours will be merged automatically as part of it.

**Pull request merged**
