### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by Hang-Lei-NOAA**
We need to add license to the repo. 
Please also copy this LGPL license files to release branch as well.

### CODE REVIEW

**Comment by climbfuji** [comment]
Ok, I will pull this commit into the release branch. Thanks!

**Comment by Hang-Lei-NOAA** [comment]
Thanks, Dom!

**Comment by climbfuji** [comment]
Question: Usually, the license sits in a separate file LICENSE.md next to README.md. See, for example, https://github.com/ufs-community/ufs-weather-model/. Should we do the same? In the public release branch, we already have a README.md with information that has nothing to do with the license.

**Comment by Hang-Lei-NOAA** [comment]
Hi, Dom

Yes, I believe that we should do that.

Thanks
Hang

**Comment by climbfuji** [comment]
Ok, I am using your README.md as LICENSE.md in the next PR. Thanks!

**Comment by aerorahul** [comment]
I have a readme.md in my feature/cleanup branches.
Please use that as a template.

**Comment by climbfuji** [comment]
> I have a readme.md in my feature/cleanup branches. Please use that as a template. On Mon, Feb 24, 2020 at 12:00 PM Hang-Lei-NOAA <notifications@github.com> wrote:
> […](#)

I couldn't find README.md in your fork's feature/cleanup or feature/cleanup2 branch. It should be called LICENSE.md to be consistent with the other UFS repositories.

**Comment by aerorahul** [comment]
Please see the bacio or any other library fork.
The template is the same for all libraries.

**Comment by climbfuji** [comment]
This PR is redundant, `LICENSE.md` was added as part of another PR.

**Pull request closed without merging**
