### PR TITLE
Tarball and Portable options

### PR DESCRIPTION
**Pull request by mark-a-potts**
This PR adds a "Portable" and a "Tarball" build option to NCEPLIBS in order to facilitate building on machines without internet connectivity. When running cmake using the "-DCMAKE_BUILD_TYPE=Tarball" option, a tarball called nceplibs.release-v2.tar.gz is created in the directory just above NCEPLIBS. This tarball contains the fully populated repos of all the source code in NCEPLIBS/src. When untarred, NCEPLIBS can then be build on any machine using the "-DCMAKE_BUILD_TYPE=Portable" option.

### CODE REVIEW

**Comment by mark-a-potts** [comment]
It occurs to me that I could re-work this a bit so that you don't have to specify a "Portable" build, but rather have CMake check to see if NCEPLIBS/src is populated, and if so, use that code by default. I'll make that change and push it up shortly, but this should allow trying to build without internet connectivity.

**Comment by climbfuji** [comment]
> It occurs to me that I could re-work this a bit so that you don't have to specify a "Portable" build, but rather have CMake check to see if NCEPLIBS/src is populated, and if so, use that code by default. I'll make that change and push it up shortly, but this should allow trying to build without internet connectivity.

This sounds great to me. I'll wait for your rework and then test it on Intel's Endeavor.

**Comment by aerorahul** [comment]
It can be portable AND buildabe.  Is there really a need for an if-else?
Why not use the `ExternalProject_Add` ability to do a git-clone?
You can still create a tarball as a target.

**Comment by mark-a-potts** [comment]
I am going to close this PR, since I think that @aerorahul's solution is a bit more elegant.

**Pull request closed without merging**
